import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

// Hardcoded S&P 500 constituents as fallback (major holdings)
const SP500_FALLBACK = [
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft Corporation", sector: "Technology" },
  { symbol: "NVDA", name: "NVIDIA Corporation", sector: "Technology" },
  { symbol: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Cyclical" },
  { symbol: "META", name: "Meta Platforms Inc.", sector: "Technology" },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A", sector: "Technology" },
  { symbol: "GOOG", name: "Alphabet Inc. Class C", sector: "Technology" },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc.", sector: "Financial Services" },
  { symbol: "LLY", name: "Eli Lilly and Company", sector: "Healthcare" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", sector: "Financial Services" },
  { symbol: "V", name: "Visa Inc.", sector: "Financial Services" },
  { symbol: "TSLA", name: "Tesla Inc.", sector: "Consumer Cyclical" },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", sector: "Healthcare" },
  { symbol: "XOM", name: "Exxon Mobil Corporation", sector: "Energy" },
  { symbol: "MA", name: "Mastercard Inc.", sector: "Financial Services" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { symbol: "PG", name: "Procter & Gamble Co.", sector: "Consumer Defensive" },
  { symbol: "COST", name: "Costco Wholesale Corporation", sector: "Consumer Defensive" },
  { symbol: "HD", name: "The Home Depot Inc.", sector: "Consumer Cyclical" },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
  { symbol: "MRK", name: "Merck & Co. Inc.", sector: "Healthcare" },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "Healthcare" },
  { symbol: "CVX", name: "Chevron Corporation", sector: "Energy" },
  { symbol: "KO", name: "The Coca-Cola Company", sector: "Consumer Defensive" },
  { symbol: "WMT", name: "Walmart Inc.", sector: "Consumer Defensive" },
  { symbol: "BAC", name: "Bank of America Corp.", sector: "Financial Services" },
  { symbol: "PEP", name: "PepsiCo Inc.", sector: "Consumer Defensive" },
  { symbol: "ORCL", name: "Oracle Corporation", sector: "Technology" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc.", sector: "Healthcare" },
  { symbol: "MCD", name: "McDonald's Corporation", sector: "Consumer Cyclical" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", sector: "Technology" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
  { symbol: "WFC", name: "Wells Fargo & Company", sector: "Financial Services" },
  { symbol: "IBM", name: "International Business Machines", sector: "Technology" },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Industrials" },
  { symbol: "GE", name: "General Electric Company", sector: "Industrials" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financial Services" },
  { symbol: "GS", name: "Goldman Sachs Group Inc.", sector: "Financial Services" },
  { symbol: "RTX", name: "Raytheon Technologies Corp.", sector: "Industrials" },
  { symbol: "QCOM", name: "Qualcomm Inc.", sector: "Technology" },
  { symbol: "NEE", name: "NextEra Energy Inc.", sector: "Utilities" },
  { symbol: "T", name: "AT&T Inc.", sector: "Communication Services" },
  { symbol: "VZ", name: "Verizon Communications Inc.", sector: "Communication Services" },
  { symbol: "INTU", name: "Intuit Inc.", sector: "Technology" },
  { symbol: "NFLX", name: "Netflix Inc.", sector: "Communication Services" },
  { symbol: "SPGI", name: "S&P Global Inc.", sector: "Financial Services" },
  { symbol: "LIN", name: "Linde plc", sector: "Basic Materials" },
  { symbol: "TXN", name: "Texas Instruments Inc.", sector: "Technology" },
  { symbol: "AXP", name: "American Express Company", sector: "Financial Services" },
  { symbol: "NOW", name: "ServiceNow Inc.", sector: "Technology" },
  { symbol: "SYK", name: "Stryker Corporation", sector: "Healthcare" },
  { symbol: "HON", name: "Honeywell International Inc.", sector: "Industrials" },
  { symbol: "CRM", name: "Salesforce Inc.", sector: "Technology" },
  { symbol: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
  { symbol: "DHR", name: "Danaher Corporation", sector: "Healthcare" },
  { symbol: "BSX", name: "Boston Scientific Corporation", sector: "Healthcare" },
  { symbol: "ADP", name: "Automatic Data Processing Inc.", sector: "Technology" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", sector: "Technology" },
  { symbol: "BLK", name: "BlackRock Inc.", sector: "Financial Services" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", sector: "Healthcare" },
  { symbol: "CI", name: "Cigna Group", sector: "Healthcare" },
  { symbol: "GILD", name: "Gilead Sciences Inc.", sector: "Healthcare" },
  { symbol: "BKNG", name: "Booking Holdings Inc.", sector: "Consumer Cyclical" },
  { symbol: "TJX", name: "TJX Companies Inc.", sector: "Consumer Cyclical" },
  { symbol: "SHW", name: "The Sherwin-Williams Company", sector: "Basic Materials" },
  { symbol: "MMC", name: "Marsh & McLennan Companies Inc.", sector: "Financial Services" },
  { symbol: "C", name: "Citigroup Inc.", sector: "Financial Services" },
  { symbol: "PLD", name: "Prologis Inc.", sector: "Real Estate" },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Financial Services" },
  { symbol: "SO", name: "Southern Company", sector: "Utilities" },
  { symbol: "DUK", name: "Duke Energy Corporation", sector: "Utilities" },
  { symbol: "CME", name: "CME Group Inc.", sector: "Financial Services" },
  { symbol: "ICE", name: "Intercontinental Exchange Inc.", sector: "Financial Services" },
  { symbol: "AON", name: "Aon plc", sector: "Financial Services" },
  { symbol: "PNC", name: "PNC Financial Services Group", sector: "Financial Services" },
  { symbol: "BMY", name: "Bristol-Myers Squibb Company", sector: "Healthcare" },
  { symbol: "TGT", name: "Target Corporation", sector: "Consumer Defensive" },
  { symbol: "DE", name: "Deere & Company", sector: "Industrials" },
  { symbol: "SCHW", name: "Charles Schwab Corporation", sector: "Financial Services" },
  { symbol: "FDX", name: "FedEx Corporation", sector: "Industrials" },
  { symbol: "UPS", name: "United Parcel Service Inc.", sector: "Industrials" },
  { symbol: "LRCX", name: "Lam Research Corporation", sector: "Technology" },
  { symbol: "KLAC", name: "KLA Corporation", sector: "Technology" },
  { symbol: "AMAT", name: "Applied Materials Inc.", sector: "Technology" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc.", sector: "Healthcare" },
  { symbol: "MDLZ", name: "Mondelez International Inc.", sector: "Consumer Defensive" },
  { symbol: "CB", name: "Chubb Limited", sector: "Financial Services" },
  { symbol: "BDX", name: "Becton, Dickinson and Company", sector: "Healthcare" },
  { symbol: "EW", name: "Edwards Lifesciences Corporation", sector: "Healthcare" },
  { symbol: "MMM", name: "3M Company", sector: "Industrials" },
  { symbol: "APH", name: "Amphenol Corporation", sector: "Technology" },
  { symbol: "UBER", name: "Uber Technologies Inc.", sector: "Technology" },
  { symbol: "SBUX", name: "Starbucks Corporation", sector: "Consumer Cyclical" },
  { symbol: "MU", name: "Micron Technology Inc.", sector: "Technology" },
  { symbol: "LOW", name: "Lowe's Companies Inc.", sector: "Consumer Cyclical" },
  { symbol: "ETN", name: "Eaton Corporation plc", sector: "Industrials" },
  { symbol: "ZTS", name: "Zoetis Inc.", sector: "Healthcare" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc.", sector: "Healthcare" },
  { symbol: "NKE", name: "Nike Inc.", sector: "Consumer Cyclical" },
  { symbol: "EQIX", name: "Equinix Inc.", sector: "Real Estate" },
  { symbol: "PANW", name: "Palo Alto Networks Inc.", sector: "Technology" },
  { symbol: "ITW", name: "Illinois Tool Works Inc.", sector: "Industrials" },
  { symbol: "PSA", name: "Public Storage", sector: "Real Estate" },
  { symbol: "COF", name: "Capital One Financial Corp.", sector: "Financial Services" },
  { symbol: "EMR", name: "Emerson Electric Co.", sector: "Industrials" },
  { symbol: "MO", name: "Altria Group Inc.", sector: "Consumer Defensive" },
  { symbol: "WM", name: "Waste Management Inc.", sector: "Industrials" },
  { symbol: "CDNS", name: "Cadence Design Systems Inc.", sector: "Technology" },
  { symbol: "SNPS", name: "Synopsys Inc.", sector: "Technology" },
  { symbol: "HCA", name: "HCA Healthcare Inc.", sector: "Healthcare" },
  { symbol: "AIG", name: "American International Group", sector: "Financial Services" },
  { symbol: "TFC", name: "Truist Financial Corporation", sector: "Financial Services" },
  { symbol: "ELV", name: "Elevance Health Inc.", sector: "Healthcare" },
  { symbol: "HUM", name: "Humana Inc.", sector: "Healthcare" },
  { symbol: "CVS", name: "CVS Health Corporation", sector: "Healthcare" },
  { symbol: "MCO", name: "Moody's Corporation", sector: "Financial Services" },
  { symbol: "APD", name: "Air Products and Chemicals Inc.", sector: "Basic Materials" },
  { symbol: "PH", name: "Parker-Hannifin Corporation", sector: "Industrials" },
  { symbol: "WELL", name: "Welltower Inc.", sector: "Real Estate" },
  { symbol: "NSC", name: "Norfolk Southern Corporation", sector: "Industrials" },
  { symbol: "CSX", name: "CSX Corporation", sector: "Industrials" },
  { symbol: "GD", name: "General Dynamics Corporation", sector: "Industrials" },
  { symbol: "LMT", name: "Lockheed Martin Corporation", sector: "Industrials" },
  { symbol: "NOC", name: "Northrop Grumman Corporation", sector: "Industrials" },
  { symbol: "BA", name: "Boeing Company", sector: "Industrials" },
  { symbol: "AEP", name: "American Electric Power Co.", sector: "Utilities" },
  { symbol: "D", name: "Dominion Energy Inc.", sector: "Utilities" },
  { symbol: "CARR", name: "Carrier Global Corporation", sector: "Industrials" },
  { symbol: "OTIS", name: "Otis Worldwide Corporation", sector: "Industrials" },
  { symbol: "SRE", name: "Sempra Energy", sector: "Utilities" },
  { symbol: "ROST", name: "Ross Stores Inc.", sector: "Consumer Cyclical" },
  { symbol: "ORLY", name: "O'Reilly Automotive Inc.", sector: "Consumer Cyclical" },
  { symbol: "MSCI", name: "MSCI Inc.", sector: "Financial Services" },
  { symbol: "GWW", name: "W.W. Grainger Inc.", sector: "Industrials" },
  { symbol: "FAST", name: "Fastenal Company", sector: "Industrials" },
  { symbol: "CTAS", name: "Cintas Corporation", sector: "Industrials" },
  { symbol: "PAYX", name: "Paychex Inc.", sector: "Technology" },
  { symbol: "MCHP", name: "Microchip Technology Inc.", sector: "Technology" },
  { symbol: "ADSK", name: "Autodesk Inc.", sector: "Technology" },
  { symbol: "KMB", name: "Kimberly-Clark Corporation", sector: "Consumer Defensive" },
  { symbol: "CL", name: "Colgate-Palmolive Company", sector: "Consumer Defensive" },
  { symbol: "PM", name: "Philip Morris International Inc.", sector: "Consumer Defensive" },
  { symbol: "STZ", name: "Constellation Brands Inc.", sector: "Consumer Defensive" },
  { symbol: "PSX", name: "Phillips 66", sector: "Energy" },
  { symbol: "VLO", name: "Valero Energy Corporation", sector: "Energy" },
  { symbol: "MPC", name: "Marathon Petroleum Corporation", sector: "Energy" },
  { symbol: "OXY", name: "Occidental Petroleum Corporation", sector: "Energy" },
  { symbol: "SLB", name: "Schlumberger Limited", sector: "Energy" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy" },
  { symbol: "EOG", name: "EOG Resources Inc.", sector: "Energy" },
  { symbol: "PXD", name: "Pioneer Natural Resources Co.", sector: "Energy" },
  { symbol: "HAL", name: "Halliburton Company", sector: "Energy" },
  { symbol: "PYPL", name: "PayPal Holdings Inc.", sector: "Financial Services" },
  { symbol: "SQ", name: "Block Inc.", sector: "Technology" },
  { symbol: "COIN", name: "Coinbase Global Inc.", sector: "Financial Services" },
  { symbol: "SHOP", name: "Shopify Inc.", sector: "Technology" },
  { symbol: "SNOW", name: "Snowflake Inc.", sector: "Technology" },
  { symbol: "DDOG", name: "Datadog Inc.", sector: "Technology" },
  { symbol: "CRWD", name: "CrowdStrike Holdings Inc.", sector: "Technology" },
  { symbol: "ZS", name: "Zscaler Inc.", sector: "Technology" },
  { symbol: "FTNT", name: "Fortinet Inc.", sector: "Technology" },
  { symbol: "NET", name: "Cloudflare Inc.", sector: "Technology" },
  { symbol: "MDB", name: "MongoDB Inc.", sector: "Technology" },
  { symbol: "TTD", name: "The Trade Desk Inc.", sector: "Technology" },
  { symbol: "RBLX", name: "Roblox Corporation", sector: "Technology" },
  { symbol: "SPOT", name: "Spotify Technology S.A.", sector: "Communication Services" },
  { symbol: "LYFT", name: "Lyft Inc.", sector: "Technology" },
  { symbol: "DASH", name: "DoorDash Inc.", sector: "Consumer Cyclical" },
  { symbol: "ABNB", name: "Airbnb Inc.", sector: "Consumer Cyclical" },
  { symbol: "RIVN", name: "Rivian Automotive Inc.", sector: "Consumer Cyclical" },
  { symbol: "LCID", name: "Lucid Group Inc.", sector: "Consumer Cyclical" },
  { symbol: "PLTR", name: "Palantir Technologies Inc.", sector: "Technology" },
  { symbol: "PATH", name: "UiPath Inc.", sector: "Technology" },
  { symbol: "AI", name: "C3.ai Inc.", sector: "Technology" },
  { symbol: "SOUN", name: "SoundHound AI Inc.", sector: "Technology" },
  { symbol: "DIS", name: "The Walt Disney Company", sector: "Communication Services" },
  { symbol: "CMCSA", name: "Comcast Corporation", sector: "Communication Services" },
  { symbol: "NWSA", name: "News Corp Class A", sector: "Communication Services" },
  { symbol: "WBD", name: "Warner Bros. Discovery Inc.", sector: "Communication Services" },
  { symbol: "PARA", name: "Paramount Global", sector: "Communication Services" },
  { symbol: "EA", name: "Electronic Arts Inc.", sector: "Communication Services" },
  { symbol: "TTWO", name: "Take-Two Interactive Software", sector: "Communication Services" },
  { symbol: "ATVI", name: "Activision Blizzard Inc.", sector: "Communication Services" },
  { symbol: "AMT", name: "American Tower Corporation", sector: "Real Estate" },
  { symbol: "CCI", name: "Crown Castle Inc.", sector: "Real Estate" },
  { symbol: "SPG", name: "Simon Property Group Inc.", sector: "Real Estate" },
  { symbol: "O", name: "Realty Income Corporation", sector: "Real Estate" },
  { symbol: "AVB", name: "AvalonBay Communities Inc.", sector: "Real Estate" },
  { symbol: "EQR", name: "Equity Residential", sector: "Real Estate" },
  { symbol: "ARE", name: "Alexandria Real Estate Equities", sector: "Real Estate" },
  { symbol: "WY", name: "Weyerhaeuser Company", sector: "Real Estate" },
  { symbol: "IP", name: "International Paper Company", sector: "Basic Materials" },
  { symbol: "NEM", name: "Newmont Corporation", sector: "Basic Materials" },
  { symbol: "FCX", name: "Freeport-McMoRan Inc.", sector: "Basic Materials" },
  { symbol: "DOW", name: "Dow Inc.", sector: "Basic Materials" },
  { symbol: "LYB", name: "LyondellBasell Industries N.V.", sector: "Basic Materials" },
  { symbol: "DD", name: "DuPont de Nemours Inc.", sector: "Basic Materials" },
  { symbol: "PPG", name: "PPG Industries Inc.", sector: "Basic Materials" },
  { symbol: "ECL", name: "Ecolab Inc.", sector: "Basic Materials" },
  { symbol: "ALB", name: "Albemarle Corporation", sector: "Basic Materials" },
  { symbol: "VMC", name: "Vulcan Materials Company", sector: "Basic Materials" },
  { symbol: "MLM", name: "Martin Marietta Materials Inc.", sector: "Basic Materials" },
  { symbol: "CF", name: "CF Industries Holdings Inc.", sector: "Basic Materials" },
  { symbol: "MOS", name: "The Mosaic Company", sector: "Basic Materials" },
  { symbol: "IEX", name: "IDEX Corporation", sector: "Industrials" },
  { symbol: "IR", name: "Ingersoll Rand Inc.", sector: "Industrials" },
  { symbol: "ROK", name: "Rockwell Automation Inc.", sector: "Industrials" },
  { symbol: "AME", name: "AMETEK Inc.", sector: "Industrials" },
  { symbol: "XYL", name: "Xylem Inc.", sector: "Industrials" },
  { symbol: "HUBB", name: "Hubbell Incorporated", sector: "Industrials" },
  { symbol: "GNRC", name: "Generac Holdings Inc.", sector: "Industrials" },
  { symbol: "KEYS", name: "Keysight Technologies Inc.", sector: "Technology" },
  { symbol: "TER", name: "Teradyne Inc.", sector: "Technology" },
  { symbol: "ANSS", name: "Ansys Inc.", sector: "Technology" },
  { symbol: "PTC", name: "PTC Inc.", sector: "Technology" },
  { symbol: "EPAM", name: "EPAM Systems Inc.", sector: "Technology" },
  { symbol: "CTSH", name: "Cognizant Technology Solutions", sector: "Technology" },
  { symbol: "ACN", name: "Accenture plc", sector: "Technology" },
  { symbol: "FIS", name: "Fidelity National Information Services", sector: "Technology" },
  { symbol: "FISV", name: "Fiserv Inc.", sector: "Technology" },
  { symbol: "GPN", name: "Global Payments Inc.", sector: "Technology" },
  { symbol: "WEX", name: "WEX Inc.", sector: "Technology" },
  { symbol: "NDAQ", name: "Nasdaq Inc.", sector: "Financial Services" },
  { symbol: "CBOE", name: "Cboe Global Markets Inc.", sector: "Financial Services" },
  { symbol: "RF", name: "Regions Financial Corporation", sector: "Financial Services" },
  { symbol: "CFG", name: "Citizens Financial Group Inc.", sector: "Financial Services" },
  { symbol: "KEY", name: "KeyCorp", sector: "Financial Services" },
  { symbol: "HBAN", name: "Huntington Bancshares Inc.", sector: "Financial Services" },
  { symbol: "FITB", name: "Fifth Third Bancorp", sector: "Financial Services" },
  { symbol: "MTB", name: "M&T Bank Corporation", sector: "Financial Services" },
  { symbol: "ZION", name: "Zions Bancorporation N.A.", sector: "Financial Services" },
  { symbol: "CMA", name: "Comerica Incorporated", sector: "Financial Services" },
  { symbol: "FHN", name: "First Horizon Corporation", sector: "Financial Services" },
  { symbol: "WAL", name: "Western Alliance Bancorporation", sector: "Financial Services" },
  { symbol: "SIVB", name: "SVB Financial Group", sector: "Financial Services" },
  { symbol: "ALLY", name: "Ally Financial Inc.", sector: "Financial Services" },
  { symbol: "SYF", name: "Synchrony Financial", sector: "Financial Services" },
  { symbol: "DFS", name: "Discover Financial Services", sector: "Financial Services" },
  { symbol: "AMP", name: "Ameriprise Financial Inc.", sector: "Financial Services" },
  { symbol: "EG", name: "Everest Group Ltd.", sector: "Financial Services" },
  { symbol: "MKL", name: "Markel Group Inc.", sector: "Financial Services" },
  { symbol: "ACGL", name: "Arch Capital Group Ltd.", sector: "Financial Services" },
  { symbol: "GL", name: "Globe Life Inc.", sector: "Financial Services" },
  { symbol: "LNC", name: "Lincoln National Corporation", sector: "Financial Services" },
  { symbol: "PFG", name: "Principal Financial Group Inc.", sector: "Financial Services" },
  { symbol: "MET", name: "MetLife Inc.", sector: "Financial Services" },
  { symbol: "PRU", name: "Prudential Financial Inc.", sector: "Financial Services" },
  { symbol: "AFL", name: "Aflac Incorporated", sector: "Financial Services" },
  { symbol: "UNM", name: "Unum Group", sector: "Financial Services" },
  { symbol: "L", name: "Loews Corporation", sector: "Financial Services" },
  { symbol: "TRV", name: "The Travelers Companies Inc.", sector: "Financial Services" },
  { symbol: "ALL", name: "The Allstate Corporation", sector: "Financial Services" },
  { symbol: "PGR", name: "Progressive Corporation", sector: "Financial Services" },
  { symbol: "HIG", name: "Hartford Financial Services Group", sector: "Financial Services" },
  { symbol: "CINF", name: "Cincinnati Financial Corporation", sector: "Financial Services" },
  { symbol: "RNR", name: "RenaissanceRe Holdings Ltd.", sector: "Financial Services" },
  { symbol: "WRB", name: "W.R. Berkley Corporation", sector: "Financial Services" },
  { symbol: "BEN", name: "Franklin Resources Inc.", sector: "Financial Services" },
  { symbol: "IVZ", name: "Invesco Ltd.", sector: "Financial Services" },
  { symbol: "TROW", name: "T. Rowe Price Group Inc.", sector: "Financial Services" },
  { symbol: "NTRS", name: "Northern Trust Corporation", sector: "Financial Services" },
  { symbol: "STT", name: "State Street Corporation", sector: "Financial Services" },
  { symbol: "BK", name: "The Bank of New York Mellon Corp.", sector: "Financial Services" },
  { symbol: "HSIC", name: "Henry Schein Inc.", sector: "Healthcare" },
  { symbol: "CAH", name: "Cardinal Health Inc.", sector: "Healthcare" },
  { symbol: "MCK", name: "McKesson Corporation", sector: "Healthcare" },
  { symbol: "ABC", name: "AmerisourceBergen Corporation", sector: "Healthcare" },
  { symbol: "BIIB", name: "Biogen Inc.", sector: "Healthcare" },
  { symbol: "ILMN", name: "Illumina Inc.", sector: "Healthcare" },
  { symbol: "IDXX", name: "IDEXX Laboratories Inc.", sector: "Healthcare" },
  { symbol: "HOLX", name: "Hologic Inc.", sector: "Healthcare" },
  { symbol: "ICLR", name: "ICON plc", sector: "Healthcare" },
  { symbol: "IQV", name: "IQVIA Holdings Inc.", sector: "Healthcare" },
  { symbol: "CRL", name: "Charles River Laboratories", sector: "Healthcare" },
  { symbol: "MTD", name: "Mettler-Toledo International Inc.", sector: "Healthcare" },
  { symbol: "PKI", name: "PerkinElmer Inc.", sector: "Healthcare" },
  { symbol: "RMD", name: "ResMed Inc.", sector: "Healthcare" },
  { symbol: "ALGN", name: "Align Technology Inc.", sector: "Healthcare" },
  { symbol: "PODD", name: "Insulet Corporation", sector: "Healthcare" },
  { symbol: "DXCM", name: "DexCom Inc.", sector: "Healthcare" },
  { symbol: "TECH", name: "Bio-Techne Corporation", sector: "Healthcare" },
  { symbol: "TFX", name: "Teleflex Incorporated", sector: "Healthcare" },
  { symbol: "ICU", name: "SeaChange International Inc.", sector: "Healthcare" },
  { symbol: "AMED", name: "Amedisys Inc.", sector: "Healthcare" },
  { symbol: "ENPH", name: "Enphase Energy Inc.", sector: "Technology" },
  { symbol: "SEDG", name: "SolarEdge Technologies Inc.", sector: "Technology" },
  { symbol: "FSLR", name: "First Solar Inc.", sector: "Technology" },
  { symbol: "RUN", name: "Sunrun Inc.", sector: "Technology" },
  { symbol: "PLUG", name: "Plug Power Inc.", sector: "Industrials" },
  { symbol: "BE", name: "Bloom Energy Corporation", sector: "Industrials" },
  { symbol: "CHPT", name: "ChargePoint Holdings Inc.", sector: "Industrials" },
  { symbol: "CEG", name: "Constellation Energy Corporation", sector: "Utilities" },
  { symbol: "PCG", name: "PG&E Corporation", sector: "Utilities" },
  { symbol: "EXC", name: "Exelon Corporation", sector: "Utilities" },
  { symbol: "ED", name: "Consolidated Edison Inc.", sector: "Utilities" },
  { symbol: "WEC", name: "WEC Energy Group Inc.", sector: "Utilities" },
  { symbol: "AWK", name: "American Water Works Company", sector: "Utilities" },
  { symbol: "PEG", name: "Public Service Enterprise Group", sector: "Utilities" },
  { symbol: "EIX", name: "Edison International", sector: "Utilities" },
  { symbol: "PPL", name: "PPL Corporation", sector: "Utilities" },
  { symbol: "CNP", name: "CenterPoint Energy Inc.", sector: "Utilities" },
  { symbol: "AES", name: "AES Corporation", sector: "Utilities" },
  { symbol: "NI", name: "NiSource Inc.", sector: "Utilities" },
  { symbol: "OGE", name: "OGE Energy Corp.", sector: "Utilities" },
  { symbol: "EVRG", name: "Evergy Inc.", sector: "Utilities" },
  { symbol: "LNT", name: "Alliant Energy Corporation", sector: "Utilities" },
  { symbol: "IDA", name: "IDACORP Inc.", sector: "Utilities" },
  { symbol: "NWE", name: "NorthWestern Corporation", sector: "Utilities" },
  { symbol: "POR", name: "Portland General Electric Company", sector: "Utilities" },
  { symbol: "BKH", name: "Black Hills Corporation", sector: "Utilities" },
  { symbol: "CBRL", name: "Cracker Barrel Old Country Store", sector: "Consumer Cyclical" },
  { symbol: "DRI", name: "Darden Restaurants Inc.", sector: "Consumer Cyclical" },
  { symbol: "CMG", name: "Chipotle Mexican Grill Inc.", sector: "Consumer Cyclical" },
  { symbol: "YUM", name: "Yum! Brands Inc.", sector: "Consumer Cyclical" },
  { symbol: "QSR", name: "Restaurant Brands International", sector: "Consumer Cyclical" },
  { symbol: "DNKN", name: "Dunkin' Brands Group Inc.", sector: "Consumer Cyclical" },
  { symbol: "JACK", name: "Jack in the Box Inc.", sector: "Consumer Cyclical" },
  { symbol: "WING", name: "Wingstop Inc.", sector: "Consumer Cyclical" },
  { symbol: "TXRH", name: "Texas Roadhouse Inc.", sector: "Consumer Cyclical" },
  { symbol: "DNUT", name: "Krispy Kreme Inc.", sector: "Consumer Cyclical" },
  { symbol: "EL", name: "Estée Lauder Companies Inc.", sector: "Consumer Defensive" },
  { symbol: "COTY", name: "Coty Inc.", sector: "Consumer Defensive" },
  { symbol: "REYN", name: "Reynolds Consumer Products Inc.", sector: "Consumer Defensive" },
  { symbol: "CHD", name: "Church & Dwight Co. Inc.", sector: "Consumer Defensive" },
  { symbol: "CLX", name: "Clorox Company", sector: "Consumer Defensive" },
  { symbol: "HRL", name: "Hormel Foods Corporation", sector: "Consumer Defensive" },
  { symbol: "SJM", name: "J.M. Smucker Company", sector: "Consumer Defensive" },
  { symbol: "GIS", name: "General Mills Inc.", sector: "Consumer Defensive" },
  { symbol: "CPB", name: "Campbell Soup Company", sector: "Consumer Defensive" },
  { symbol: "K", name: "Kellogg Company", sector: "Consumer Defensive" },
  { symbol: "HSY", name: "The Hershey Company", sector: "Consumer Defensive" },
  { symbol: "MKC", name: "McCormick & Company Inc.", sector: "Consumer Defensive" },
  { symbol: "SYY", name: "Sysco Corporation", sector: "Consumer Defensive" },
  { symbol: "USFD", name: "US Foods Holding Corp.", sector: "Consumer Defensive" },
  { symbol: "PFGC", name: "Performance Food Group Company", sector: "Consumer Defensive" },
  { symbol: "SPTN", name: "SpartanNash Company", sector: "Consumer Defensive" },
  { symbol: "KR", name: "The Kroger Co.", sector: "Consumer Defensive" },
  { symbol: "ACI", name: "Albertsons Companies Inc.", sector: "Consumer Defensive" },
  { symbol: "SFM", name: "Sprouts Farmers Market Inc.", sector: "Consumer Defensive" },
  { symbol: "WINN", name: "Winn-Dixie Stores Inc.", sector: "Consumer Defensive" },
  { symbol: "AMCR", name: "Amcor plc", sector: "Consumer Defensive" },
  { symbol: "SEE", name: "Sealed Air Corporation", sector: "Consumer Defensive" },
  { symbol: "BLL", name: "Ball Corporation", sector: "Consumer Defensive" },
  { symbol: "CCK", name: "Crown Holdings Inc.", sector: "Consumer Defensive" },
  { symbol: "BERY", name: "Berry Global Group Inc.", sector: "Consumer Defensive" },
  { symbol: "OI", name: "O-I Glass Inc.", sector: "Consumer Defensive" },
  { symbol: "PKG", name: "Packaging Corporation of America", sector: "Basic Materials" },
  { symbol: "WRK", name: "WestRock Company", sector: "Basic Materials" },
  { symbol: "SON", name: "Sonoco Products Company", sector: "Basic Materials" },
  { symbol: "CLF", name: "Cleveland-Cliffs Inc.", sector: "Basic Materials" },
  { symbol: "NUE", name: "Nucor Corporation", sector: "Basic Materials" },
  { symbol: "STLD", name: "Steel Dynamics Inc.", sector: "Basic Materials" },
  { symbol: "RS", name: "Reliance Steel & Aluminum Co.", sector: "Basic Materials" },
  { symbol: "CMC", name: "Commercial Metals Company", sector: "Basic Materials" },
  { symbol: "X", name: "United States Steel Corporation", sector: "Basic Materials" },
  { symbol: "AA", name: "Alcoa Corporation", sector: "Basic Materials" },
  { symbol: "CENX", name: "Century Aluminum Company", sector: "Basic Materials" },
  { symbol: "KALU", name: "Kaiser Aluminum Corporation", sector: "Basic Materials" },
];

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { query } = await req.json();
    const FMP_API_KEY = Deno.env.get("FMP_API_KEY");
    if (!FMP_API_KEY) throw new Error("FMP_API_KEY is not configured");

    if (query === "__sp500__") {
      // Try FMP API first, fall back to hardcoded list
      try {
        const res = await fetch(`https://financialmodelingprep.com/api/v3/sp500_constituent?apikey=${FMP_API_KEY}`);
        const data = await res.json();
        if (Array.isArray(data) && data.length > 0) {
          const tickers = data.map((d: any) => ({
            symbol: d.symbol,
            name: d.name,
            sector: d.sector,
          }));
          return new Response(JSON.stringify(tickers), {
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          });
        }
      } catch {
        // Fall through to hardcoded list
      }
      // Return hardcoded fallback
      return new Response(JSON.stringify(SP500_FALLBACK), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Try FMP search first
    let results: Array<{ symbol: string; name: string; exchange?: string }> = [];
    try {
      const res = await fetch(`https://financialmodelingprep.com/api/v3/search?query=${encodeURIComponent(query)}&limit=10&apikey=${FMP_API_KEY}`);
      const data = await res.json();
      if (Array.isArray(data) && data.length > 0) {
        results = data.map((d: any) => ({
          symbol: d.symbol,
          name: d.name || d.companyName,
          exchange: d.exchange || d.exchangeShortName,
        }));
      } else {
        // FMP returned error or empty — log and fall through to local search
        if (!Array.isArray(data)) {
          console.warn("FMP search error, using local fallback:", JSON.stringify(data).slice(0, 150));
        }
      }
    } catch (e) {
      console.warn("FMP search failed, using local fallback:", e);
    }

    // If FMP returned nothing, search the hardcoded list
    if (results.length === 0) {
      const q = query.toUpperCase();
      results = SP500_FALLBACK.filter(
        (s) => s.symbol.includes(q) || s.name.toUpperCase().includes(q)
      ).slice(0, 10).map((s) => ({
        symbol: s.symbol,
        name: s.name,
        exchange: "US",
      }));
    }

    return new Response(JSON.stringify(results), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("search-tickers error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});

